apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-authentication-operator
  name: authentication-operator
  labels:
    app: authentication-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-authentication
  name: oauth-openshift
  labels:
    app: oauth-openshift
